backend:
  name: github
  repo: tumblenet/TumbleCraftJava
  base_url: http://github.tumblenet.ga/TumbleCraftJava/

#publish_mode: editorial_workflow
media_folder: "uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "post"
    label: "Multiple Redirect"
    folder: "_posts/"
    create: true
    delete: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "multredirect"}
      - {label: "Title", name: "title", widget: "string", required="true"}
      - label: "URLs"
        label_singular: "URL"
        name: "hrefList"
        widget: "list"
        required: "true"
        fields:
          - {label: "URL", name: "href", widget: "string",required="true", default: "http://"}
      #- {label: "date", name: "date", widget: "datetime", required="true"}
